### ISSUE TITLE
jed time command [1.10.2]

### ISSUE THREAD

**Issue by vin0m** [maruohon/justenoughdimensions#23]
When I use the "/jed time set" command it responds saying the time is set but it doesn't change the time.  Any ideas what might be going on here?

**Comment by maruohon** [comment]
If you do this in a non-overworld dimension, so a custom dimension or the nether or the end for example, this will only work if you have WorldInfo overrides enabled for that dimension. Otherwise it's not possible for that dimension to have a time separate from the overworld, and the time command basically does nothing in that case.

I should probably add warning messages to these commands in case the WorldInfo of that dimension is `DerivedWorldInfo`, meaning that the command didn't work...

**Comment by vin0m** [comment]
Yea, I went back and read the mod page and noticed a note requiring the worldinfo override and got it to work.  Thanks for the awesome mod btw.  Good work.
