### ISSUE TITLE
Hostile Mobs cannot spawn in custom dimensions

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/justenoughdimensions#3]
I have a custom dimension that I created to use as an industrial area, and I cannot get any hostile mobs to spawn there. I was in peaceful difficultly, then changed it to normal to test out some Immersive Engineering turrets, but no hostiles would spawn. I grabbed a spawn egg from the creative inventory, but the mobs would appear then immediately disappear, just like in peaceful.

It would seem that custom dimensions don't pick up on the difficultly change right away for some reason.

**Comment by maruohon** [comment]
This has now been fixed in version 1.3.4.

Note that if you are using per-dimension WorldInfo, then you need to use the `/jed difficulty` command for any such dimensions, instead of the vanilla `/difficulty` command.

Basically if you are using WorldInfo overrides, then the custom dimensions will inherit the values from the overworld when first created, but the changes to the overworld settings (ie. with the vanilla gamerule/difficulty etc commands) will not affect the custom dimensions after that. You have to use the /jed command variants instead for such dimensions.

**Comment by BrisingrAerowing** [comment]
Gotcha. I'll get the new version in a minute. Going to finish an Ender IO powered spawner based Iron Golem farm first (big 20 x 20 x 11 cube, with four spawners inside it. Each farm can be individually controlled from a small command center)
