### ISSUE TITLE
Feature Request: Add keepInventory to supported keys in worldinfo

### ISSUE THREAD

**Issue by elderpyre** [maruohon/justenoughdimensions#4]
Please add the gamerule 'keepInventory' to the supported keys in worldinfo. If this is already possible, please add an example to the curseforge page of how to use a command in the json.

Thanks!

**Comment by maruohon** [comment]
Gamerules are supported, but they can't currently be added via the in-game dimbuilder command, only directly in the dimensions.json file. I might take a look at refactoring some of the relevant code when I get the chance, to make it possible to add and remove them via the dimbuilder command.

For now, you can set them in the json file like this: https://pastebin.com/GakmHRvm
So basically nest a *GameRules* object inside the *worldinfo* or a *worldinfo_onetime* (this one is preferred, so that they won't get (re-)set every time the dimension loads) object and then add the rules inside there.
