### ISSUE TITLE
Conflict with SBM-DeadMansSatchel

### ISSUE THREAD

**Issue by ztblat** [maruohon/justenoughdimensions#70]
https://mclo.gs/DNPyIBM
https://mclo.gs/WRtn2YS
Using SBM-DeadMansSatchel in Custom Dimensions

**Comment by ztblat** [comment]
> That seems to be an issue in that mod, I don't see anything related to JED in the stack trace.

The author of that mod has given up.

**Comment by maruohon** [comment]
Well there is nothing to be done from JED's side for that crash. It needs to be fixed in that mod.

However looking at their code, it might be fixed if you use the `"load_on_start": true` option for all dimensions you add via JED.

Also looks like you have some beta version of that mod? There is a 1.0.0 version on CurseForge. Although that probably changes nothing for this crash, but it might fix other issues.

**Comment by ztblat** [comment]
Thank you so much. Problem solved.
